#
# Differential outputs to back panel MOSFET drivers
#
# FMC2 LA_00_P
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[0]}]
# FMC2 LA_00_N
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[0]}]
# FMC2 LA_01_P
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[1]}]
# FMC2 LA_01_N
set_property -dict {PACKAGE_PIN AB24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[1]}]
# FMC2 LA_02_P
set_property -dict {PACKAGE_PIN AE22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[2]}]
# FMC2 LA_02_N
set_property -dict {PACKAGE_PIN AF22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[2]}]
# FMC2 LA_03_P
set_property -dict {PACKAGE_PIN AD26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[3]}]
# FMC2 LA_03_N
set_property -dict {PACKAGE_PIN AE26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[3]}]
# FMC2 LA_04_P
set_property -dict {PACKAGE_PIN V21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[4]}]
# FMC2 LA_04_N
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[4]}]
# FMC2 LA_05_P
set_property -dict {PACKAGE_PIN AB26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[5]}]
# FMC2 LA_05_N
set_property -dict {PACKAGE_PIN AC26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[5]}]
# FMC2 LA_06_P
set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[6]}]
# FMC2 LA_06_N
set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[6]}]
# FMC2 LA_07_P
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[7]}]
# FMC2 LA_07_N
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[7]}]
# FMC2 LA_08_P
set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[8]}]
# FMC2 LA_08_N
set_property -dict {PACKAGE_PIN AC24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[8]}]
# FMC2 LA_09_P
set_property -dict {PACKAGE_PIN U26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[9]}]
# FMC2 LA_09_N
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[9]}]
# FMC2 LA_10_P
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[10]}]
# FMC2 LA_10_N
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[10]}]
# FMC2 LA_11_P
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[11]}]
# FMC2 LA_11_N
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[11]}]
# FMC2 LA_12_P
set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[12]}]
# FMC2 LA_12_N
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[12]}]
# FMC2 LA_13_P
set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[13]}]
# FMC2 LA_13_N
set_property -dict {PACKAGE_PIN V24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[13]}]
# FMC2 LA_14_P
set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[14]}]
# FMC2 LA_14_N
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[14]}]
# FMC2 LA_15_P
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[15]}]
# FMC2 LA_15_N
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[15]}]
# FMC2 LA_16_P
set_property -dict {PACKAGE_PIN W25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[16]}]
# FMC2 LA_16_N
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[16]}]
# FMC2 LA_17_P
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[17]}]
# FMC2 LA_17_N
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[17]}]
# FMC2 LA_18_P
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[18]}]
# FMC2 LA_18_N
set_property -dict {PACKAGE_PIN F24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[18]}]
# FMC2 LA_19_P
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[19]}]
# FMC2 LA_19_N
set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[19]}]
# FMC2 LA_20_P
set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[20]}]
# FMC2 LA_20_N
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[20]}]
# FMC2 LA_21_P
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[21]}]
# FMC2 LA_21_N
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[21]}]
# FMC2 LA_22_P
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[22]}]
# FMC2 LA_22_N
set_property -dict {PACKAGE_PIN D25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[22]}]
# FMC2 LA_23_P
set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[23]}]
# FMC2 LA_23_N
set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[23]}]
# FMC2 LA_24_P
set_property -dict {PACKAGE_PIN J24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[24]}]
# FMC2 LA_24_N
set_property -dict {PACKAGE_PIN J25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[24]}]
# FMC2 LA_25_P
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[25]}]
# FMC2 LA_25_N
set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[25]}]
# FMC2 LA_26_P
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[26]}]
# FMC2 LA_26_N
set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[26]}]
# FMC2 LA_27_P
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[27]}]
# FMC2 LA_27_N
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[27]}]
# FMC2 LA_28_P
set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[28]}]
# FMC2 LA_28_N
set_property -dict {PACKAGE_PIN G26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[28]}]
# FMC2 LA_29_P
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[29]}]
# FMC2 LA_29_N
set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[29]}]
# FMC2 LA_30_P
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[30]}]
# FMC2 LA_30_N
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[30]}]
# FMC2 LA_31_P
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[31]}]
# FMC2 LA_31_N
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[31]}]
# FMC2 LA_32_P
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[32]}]
# FMC2 LA_32_N
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[32]}]
# FMC2 LA_33_P
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[33]}]
# FMC2 LA_33_N
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[33]}]
# FMC2 HA_00_P
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[34]}]
# FMC2 HA_00_N
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[34]}]
# FMC2 HA_01_P
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[35]}]
# FMC2 HA_01_N
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[35]}]
# FMC2 HA_02_P
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[36]}]
# FMC2 HA_02_N
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[36]}]
# FMC2 HA_03_P
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[37]}]
# FMC2 HA_03_N
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[37]}]
# FMC2 HA_04_P
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[38]}]
# FMC2 HA_04_N
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[38]}]
# FMC2 HA_05_P
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[39]}]
# FMC2 HA_05_N
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[39]}]
# FMC2 HA_06_P
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[40]}]
# FMC2 HA_06_N
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[40]}]
# FMC2 HA_07_P
set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[41]}]
# FMC2 HA_07_N
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[41]}]
# FMC2 HA_08_P
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[42]}]
# FMC2 HA_08_N
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[42]}]
# FMC2 HA_09_P
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[43]}]
# FMC2 HA_09_N
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[43]}]
# FMC2 HA_10_P
set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[44]}]
# FMC2 HA_10_N
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[44]}]
# FMC2 HA_11_P
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[45]}]
# FMC2 HA_11_N
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[45]}]
# FMC2 HA_12_P
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[46]}]
# FMC2 HA_12_N
set_property -dict {PACKAGE_PIN L24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[46]}]
# FMC2 HA_13_P
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[47]}]
# FMC2 HA_13_N
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[47]}]
# FMC2 HA_14_P
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[48]}]
# FMC2 HA_14_N
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[48]}]
# FMC2 HA_15_P
set_property -dict {PACKAGE_PIN R25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[49]}]
# FMC2 HA_15_N
set_property -dict {PACKAGE_PIN P25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[49]}]
# FMC2 HA_16_P
set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[50]}]
# FMC2 HA_16_N
set_property -dict {PACKAGE_PIN P26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[50]}]
# FMC2 HA_17_P
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[51]}]
# FMC2 HA_17_N
set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[51]}]
# FMC2 HA_18_P
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[52]}]
# FMC2 HA_18_N
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[52]}]
# FMC2 HA_19_P
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[53]}]
# FMC2 HA_19_N
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[53]}]
# FMC2 HA_20_P
set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[54]}]
# FMC2 HA_20_N
set_property -dict {PACKAGE_PIN N23 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[54]}]
# FMC2 HA_21_P
set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[55]}]
# FMC2 HA_21_N
set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[55]}]
# FMC2 HA_22_P
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[56]}]
# FMC2 HA_22_N
set_property -dict {PACKAGE_PIN M26 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[56]}]
# FMC2 HA_23_P
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_P[57]}]
# FMC2 HA_23_N
set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC2_N[57]}]
# FMC1 LA_00_P
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[0]}]
# FMC1 LA_00_N
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[0]}]
# FMC1 LA_01_P
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[1]}]
# FMC1 LA_01_N
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[1]}]
# FMC1 LA_02_P
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[2]}]
# FMC1 LA_02_N
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[2]}]
# FMC1 LA_03_P
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[3]}]
# FMC1 LA_03_N
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[3]}]
# FMC1 LA_04_P
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[4]}]
# FMC1 LA_04_N
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[4]}]
# FMC1 LA_05_P
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[5]}]
# FMC1 LA_05_N
set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[5]}]
# FMC1 LA_06_P
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[6]}]
# FMC1 LA_06_N
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[6]}]
# FMC1 LA_07_P
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[7]}]
# FMC1 LA_07_N
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[7]}]
# FMC1 LA_08_P
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[8]}]
# FMC1 LA_08_N
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[8]}]
# FMC1 LA_09_P
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[9]}]
# FMC1 LA_09_N
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[9]}]
# FMC1 LA_10_P
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[10]}]
# FMC1 LA_10_N
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[10]}]
# FMC1 LA_11_P
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[11]}]
# FMC1 LA_11_N
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[11]}]
# FMC1 LA_12_P
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[12]}]
# FMC1 LA_12_N
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[12]}]
# FMC1 LA_13_P
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[13]}]
# FMC1 LA_13_N
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[13]}]
# FMC1 LA_14_P
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[14]}]
# FMC1 LA_14_N
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[14]}]
# FMC1 LA_15_P
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[15]}]
# FMC1 LA_15_N
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[15]}]
# FMC1 LA_16_P
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[16]}]
# FMC1 LA_16_N
set_property -dict {PACKAGE_PIN K17  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[16]}]
# FMC1 LA_17_P
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[17]}]
# FMC1 LA_17_N
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[17]}]
# FMC1 LA_18_P
set_property -dict {PACKAGE_PIN C12  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[18]}]
# FMC1 LA_18_N
set_property -dict {PACKAGE_PIN C11  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[18]}]
# FMC1 LA_19_P
set_property -dict {PACKAGE_PIN H14  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[19]}]
# FMC1 LA_19_N
set_property -dict {PACKAGE_PIN G14  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[19]}]
# FMC1 LA_20_P
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[20]}]
# FMC1 LA_20_N
set_property -dict {PACKAGE_PIN A15  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[20]}]
# FMC1 LA_21_P
set_property -dict {PACKAGE_PIN D14  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[21]}]
# FMC1 LA_21_N
set_property -dict {PACKAGE_PIN D13  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[21]}]
# FMC1 LA_22_P
set_property -dict {PACKAGE_PIN B14  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[22]}]
# FMC1 LA_22_N
set_property -dict {PACKAGE_PIN A14  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[22]}]
# FMC1 LA_23_P
set_property -dict {PACKAGE_PIN G12  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[23]}]
# FMC1 LA_23_N
set_property -dict {PACKAGE_PIN F12  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[23]}]
# FMC1 LA_24_P
set_property -dict {PACKAGE_PIN A9  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[24]}]
# FMC1 LA_24_N
set_property -dict {PACKAGE_PIN A8   IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[24]}]
# FMC1 LA_25_P
set_property -dict {PACKAGE_PIN G10  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[25]}]
# FMC1 LA_25_N
set_property -dict {PACKAGE_PIN G9   IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[25]}]
# FMC1 LA_26_P
set_property -dict {PACKAGE_PIN E13  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[26]}]
# FMC1 LA_26_N
set_property -dict {PACKAGE_PIN E12  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[26]}]
# FMC1 LA_27_P
set_property -dict {PACKAGE_PIN F14  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[27]}]
# FMC1 LA_27_N
set_property -dict {PACKAGE_PIN F13  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[27]}]
# FMC1 LA_28_P
set_property -dict {PACKAGE_PIN J13  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[28]}]
# FMC1 LA_28_N
set_property -dict {PACKAGE_PIN H13  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[28]}]
# FMC1 LA_29_P
set_property -dict {PACKAGE_PIN F9   IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[29]}]
# FMC1 LA_29_N
set_property -dict {PACKAGE_PIN F8   IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[29]}]
# FMC1 LA_30_P
set_property -dict {PACKAGE_PIN B12  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[30]}]
# FMC1 LA_30_N
set_property -dict {PACKAGE_PIN B11  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[30]}]
# FMC1 LA_31_P
set_property -dict {PACKAGE_PIN A13  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[31]}]
# FMC1 LA_31_N
set_property -dict {PACKAGE_PIN A12  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[31]}]
# FMC1 LA_32_P
set_property -dict {PACKAGE_PIN C14  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[32]}]
# FMC1 LA_32_N
set_property -dict {PACKAGE_PIN C13  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[32]}]
# FMC1 LA_33_P
set_property -dict {PACKAGE_PIN B10  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_P[33]}]
# FMC1 LA_33_N
set_property -dict {PACKAGE_PIN A10  IOSTANDARD LVDS_25} [get_ports {DRIVER_FMC1_N[33]}]
# BANK 32 IO_L1_P
set_property -dict {PACKAGE_PIN AE17 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[0]}]
# BANK 32 IO_L1_N
set_property -dict {PACKAGE_PIN AF17 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[0]}]
# BANK 32 IO_L2_P
set_property -dict {PACKAGE_PIN AF14 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[1]}]
# BANK 32 IO_L2_N
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[1]}]
# BANK 32 IO_L3_P
set_property -dict {PACKAGE_PIN AE18 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[2]}]
# BANK 32 IO_L3_N
set_property -dict {PACKAGE_PIN AF18 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[2]}]
# BANK 32 IO_L4_P
set_property -dict {PACKAGE_PIN AD15 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[3]}]
# BANK 32 IO_L4_N
set_property -dict {PACKAGE_PIN AE15 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[3]}]
# BANK 32 IO_L5_P
set_property -dict {PACKAGE_PIN AF19 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[4]}]
# BANK 32 IO_L5_N
set_property -dict {PACKAGE_PIN AF20 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[4]}]
# BANK 32 IO_L7_P
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[5]}]
# BANK 32 IO_L7_N
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[5]}]
# BANK 32 IO_L8_P
set_property -dict {PACKAGE_PIN AC14 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[6]}]
# BANK 32 IO_L8_N
set_property -dict {PACKAGE_PIN AD14 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[6]}]
# BANK 32 IO_L9_P
set_property -dict {PACKAGE_PIN Y15  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[7]}]
# BANK 32 IO_L9_N
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[7]}]
# BANK 32 IO_L10_P
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[8]}]
# BANK 32 IO_L10_N
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[8]}]
# BANK 32 IO_L11_P
set_property -dict {PACKAGE_PIN AA17 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[9]}]
# BANK 32 IO_L11_N
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[9]}]
# BANK 32 IO_L13_P
set_property -dict {PACKAGE_PIN AC18 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[10]}]
# BANK 32 IO_L13_N
set_property -dict {PACKAGE_PIN AD18 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[10]}]
# BANK 32 IO_L14_P
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[11]}]
# BANK 32 IO_L14_N
set_property -dict {PACKAGE_PIN AC17 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[11]}]
# BANK 32 IO_L15_P
set_property -dict {PACKAGE_PIN AD20 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[12]}]
# BANK 32 IO_L15_N
set_property -dict {PACKAGE_PIN AE20 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[12]}]
# BANK 32 IO_L16_P
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[13]}]
# BANK 32 IO_L16_N
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[13]}]
# BANK 32 IO_L17_P
set_property -dict {PACKAGE_PIN AC19 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[14]}]
# BANK 32 IO_L17_N
set_property -dict {PACKAGE_PIN AD19 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[14]}]
# BANK 32 IO_L20_P
set_property -dict {PACKAGE_PIN V16  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[15]}]
# BANK 32 IO_L20_N
set_property -dict {PACKAGE_PIN V17  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[15]}]
# BANK 32 IO_L21_P
set_property -dict {PACKAGE_PIN W18  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[16]}]
# BANK 32 IO_L21_N
set_property -dict {PACKAGE_PIN W19  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[16]}]
# BANK 32 IO_L22_P
set_property -dict {PACKAGE_PIN W15  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[17]}]
# BANK 32 IO_L22_N
set_property -dict {PACKAGE_PIN W16  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[17]}]
# BANK 32 IO_L23_P
set_property -dict {PACKAGE_PIN V18  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[18]}]
# BANK 32 IO_L23_N
set_property -dict {PACKAGE_PIN V19  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[18]}]
# BANK 32 IO_L24_P
set_property -dict {PACKAGE_PIN V14  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[19]}]
# BANK 32 IO_L24_N
set_property -dict {PACKAGE_PIN W14  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[19]}]
# BANK 34 IO_L1_P
set_property -dict {PACKAGE_PIN U6   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[20]}]
# BANK 34 IO_L1_N
set_property -dict {PACKAGE_PIN U5  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[20]}]
# BANK 34 IO_L2_P
set_property -dict {PACKAGE_PIN U2   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[21]}]
# BANK 34 IO_L2_N
set_property -dict {PACKAGE_PIN U1   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[21]}]
# BANK 34 IO_L3_P
set_property -dict {PACKAGE_PIN W6   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[22]}]
# BANK 34 IO_L3_N
set_property -dict {PACKAGE_PIN W5   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[22]}]
# BANK 34 IO_L4_P
set_property -dict {PACKAGE_PIN V3   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[23]}]
# BANK 34 IO_L4_N
set_property -dict {PACKAGE_PIN W3   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[23]}]
# BANK 34 IO_L5_P
set_property -dict {PACKAGE_PIN U7   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[24]}]
# BANK 34 IO_L5_N
set_property -dict {PACKAGE_PIN V6 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[24]}]
# BANK 34 IO_L7_P
set_property -dict {PACKAGE_PIN Y3   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[25]}]
# BANK 34 IO_L7_N
set_property -dict {PACKAGE_PIN Y2   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[25]}]
# BANK 34 IO_L8_P
set_property -dict {PACKAGE_PIN V2   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[26]}]
# BANK 34 IO_L8_N
set_property -dict {PACKAGE_PIN V1   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[26]}]
# BANK 34 IO_L9_P
set_property -dict {PACKAGE_PIN AB1  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[27]}]
# BANK 34 IO_L9_N
set_property -dict {PACKAGE_PIN AC1   IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[27]}]
# BANK 34 IO_L10_P
set_property -dict {PACKAGE_PIN W1 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[28]}]
# BANK 34 IO_L10_N
set_property -dict {PACKAGE_PIN Y1  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[28]}]
# BANK 34 IO_L11_P
set_property -dict {PACKAGE_PIN AB2  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[29]}]
# BANK 34 IO_L11_N
set_property -dict {PACKAGE_PIN AC2  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[29]}]
# BANK 34 IO_L13_P
set_property -dict {PACKAGE_PIN AA4  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[30]}]
# BANK 34 IO_L13_N
set_property -dict {PACKAGE_PIN AB4  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[30]}]
# BANK 34 IO_L14_P
set_property -dict {PACKAGE_PIN AC4  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[31]}]
# BANK 34 IO_L14_N
set_property -dict {PACKAGE_PIN AC3  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[31]}]
# BANK 34 IO_L15_P
set_property -dict {PACKAGE_PIN AA5  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[32]}]
# BANK 34 IO_L15_N
set_property -dict {PACKAGE_PIN AB5  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[32]}]
# BANK 34 IO_L16_P
set_property -dict {PACKAGE_PIN AB6  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[33]}]
# BANK 34 IO_L16_N
set_property -dict {PACKAGE_PIN AC6  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[33]}]
# BANK 34 IO_L17_P
set_property -dict {PACKAGE_PIN Y6  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[34]}]
# BANK 34 IO_L17_N
set_property -dict {PACKAGE_PIN Y5  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[34]}]
# BANK 34 IO_L20_P
set_property -dict {PACKAGE_PIN AD1  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[35]}]
# BANK 34 IO_L20_N
set_property -dict {PACKAGE_PIN AE1  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[35]}]
# BANK 34 IO_L21_P
set_property -dict {PACKAGE_PIN AF5  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[36]}]
# BANK 34 IO_L21_N
set_property -dict {PACKAGE_PIN AF4  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[36]}]
# BANK 34 IO_L22_P
set_property -dict {PACKAGE_PIN AE3 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[37]}]
# BANK 34 IO_L22_N
set_property -dict {PACKAGE_PIN AE2  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[37]}]
# BANK 34 IO_L23_P
set_property -dict {PACKAGE_PIN AE6  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[38]}]
# BANK 34 IO_L23_N
set_property -dict {PACKAGE_PIN AE5  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[38]}]
# BANK 34 IO_L24_P
set_property -dict {PACKAGE_PIN AF3  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[39]}]
# BANK 34 IO_L24_N
set_property -dict {PACKAGE_PIN AF2  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[39]}]
# BANK 33 IO_L9_P
set_property -dict {PACKAGE_PIN AC8  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[40]}]
# BANK 33 IO_L9_N
set_property -dict {PACKAGE_PIN AD8  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[40]}]
# BANK 33 IO_L10_P
set_property -dict {PACKAGE_PIN AB7  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[41]}]
# BANK 33 IO_L10_N
set_property -dict {PACKAGE_PIN AC7  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[41]}]
# BANK 33 IO_L11_P
set_property -dict {PACKAGE_PIN AA9  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[42]}]
# BANK 33 IO_L11_N
set_property -dict {PACKAGE_PIN AB9  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[42]}]
# BANK 33 IO_L13_P
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[43]}]
# BANK 33 IO_L13_N
set_property -dict {PACKAGE_PIN AC11 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[43]}]
# BANK 33 IO_L14_P
set_property -dict {PACKAGE_PIN AA10  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[44]}]
# BANK 33 IO_L14_N
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[44]}]
# BANK 33 IO_L15_P
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[45]}]
# BANK 33 IO_L15_N
set_property -dict {PACKAGE_PIN AC12 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[45]}]
# BANK 33 IO_L16_P
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[46]}]
# BANK 33 IO_L16_N
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[46]}]
# BANK 33 IO_L17_P
set_property -dict {PACKAGE_PIN AC13 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[47]}]
# BANK 33 IO_L17_N
set_property -dict {PACKAGE_PIN AD13 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[47]}]
# BANK 33 IO_L20_P
set_property -dict {PACKAGE_PIN AD10 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[48]}]
# BANK 33 IO_L20_N
set_property -dict {PACKAGE_PIN AE10 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[48]}]
# BANK 33 IO_L21_P
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[49]}]
# BANK 33 IO_L21_N
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[49]}]
# BANK 33 IO_L22_P
set_property -dict {PACKAGE_PIN AE8  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[50]}]
# BANK 33 IO_L22_N
set_property -dict {PACKAGE_PIN AF8  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[50]}]
# BANK 33 IO_L23_P
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[51]}]
# BANK 33 IO_L23_N
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[51]}]
# BANK 33 IO_L24_P
set_property -dict {PACKAGE_PIN AF10 IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_P[52]}]
# BANK 33 IO_L24_N
set_property -dict {PACKAGE_PIN AF9  IOSTANDARD DIFF_HSTL_I_DCI} [get_ports {DRIVER_SODIMM_N[52]}]

# FMC2_CLK1_M2C -- Used for diagnostics
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS25} [get_ports FMC2_CLK1_M2C_P]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS25} [get_ports FMC2_CLK1_M2C_N]
