stages:
  - prepare
  - gateware
  - software

default:
  tags:
    - xilinx

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2020.2.2/Vivado/2020.2
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2020.2.2/Vitis/2020.2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gw_evfr_marble:
  before_script:
    - cd gateware/syn/evfr_marble && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH time make evfr_marble_top.bit && PATH=$XILINX_VIVADO/bin:$PATH time make evfr_marble_top.mmi
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - gateware/syn/evfr_marble/evfr_marble_top.bit
      - gateware/syn/evfr_marble/evfr_marble_top.mmi
      - gateware/syn/evfr_marble/_xilinx/evfr_marble_top/*.runs/impl_1/*.rpt
      - gateware/syn/evfr_marble/bd.xsa

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
sw_evfr_marble:
  before_script:
    - cd software/app/evfr
  stage: software
  script:
    - make TARGET=evfr_marble clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/microblaze/lin/bin:$PATH time make TARGET=evfr_marble
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_evfr_marble
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 7 days
    paths:
      - software/app/evfr/evfr_marble.elf
      - software/app/evfr/evfr_marble.elf.size
      - software/app/evfr/downloadEVFR.bit
